[project]
name = "sam-lambda"
version = "0.1.0"
description = "SAM用の開発環境"
readme = "README.md"
dependencies = [
    "aws-lambda-powertools>=3.34.0",
    "pydantic>=2.13.5",
]

[dependency-groups]
dev = [
  "aws-cdk-lib>=2.230.0",
  "constructs>=10.4.3",
  "moto>=5.1.16",
  "pytest>=8.3.5",
  "pytest-cov>=6.1.1",
  "pytest-mock>=3.14.1",
]

[tool.pytest.ini_options]
addopts = "-v"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
pythonpath = [
  "src",
]
testpaths = [
  "tests",
]

[tool.ruff]
line-length = 120
fix = true
exclude = [
  ".venv",
  "__pycache__",
  "migrations",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "INP001",  # __init__.pyがない
  "EXE002",  # シバンがない
]
unfixable = []
logger-objects = ["src.library.logger.LOGGER"]

[tool.ruff.lint.pylint]
max-args = 6

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",  # assert を許可
  "D",  # docstring 不要
]

[tool.uv]
package = true
