AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: |
  SAM Lambda Sample Application

Globals:
  Function:
    Runtime: python3.14
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512

Resources:
  # ============================================================
  # API Gateway HTTP API
  # ============================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  # ============================================================
  # API Lambda IAM Role
  #
  # Application connects using custom DB role "app_user".
  # Therefore this role requires dsql:DbConnect.
  # ============================================================
  ApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        # CloudWatch Logs
        - PolicyName: LambdaLogging
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # ============================================================
  # API Lambda
  # ============================================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.app.lambda_handler
      Role: !GetAtt ApiFunctionRole.Arn
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

# ============================================================
# Outputs
# ============================================================
Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub
      - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com
      - ApiId: !Ref HttpApi
